Robustspotdetection
mehta-lab/multiSero pull request #34
Opened 2020-04-08 04:56 UTC by jennyfolkesson

I believe this should be stable now, but @bryantChhun should have a final say before this is merged. I wanted to start the code review at least.

One question - it looks like a lot of images are displayed now as you're running, and that makes the run pretty slow, plus you have all these plots popping up. What about changing this to write only?

2020-04-08 13:41 UTC, mattersoflight commented
I suggest @smguo merge his recent changes that improve the estimation of OD into this branch, and then we test it against March 25 and Apr 4 datasets. 

@jennyfolkesson these plots are to catch edge cases as the pipeline developed, but they are all invoked if debug is enabled. If there are any plots that are outside if debug: flag, we should move them there.

2020-04-08 21:10 UTC, bryantChhun commented
There is a minor issue with the OD calculation -- both the cropped image and the background need to be on range 0-1, float64, not inverted

I will submit a PR to robostspotdetection

2020-04-10 00:30 UTC, jennyfolkesson commented
@mattersoflight @bryantChhun @smguo I believe this PR is ready for review now.

2020-04-10 21:07 UTC, smguo commented
I tested both workflows on the COVID_0408 plate data. The fit workflow runs fine after fixing the lines I noted in comments, but the interpolation workflow errors out on C1, which I didn't encounter in my branch. I'll submit a separate PR to fix the issue with interpolation workflow.

The fit approach seems to work well on he COVID_0408 plate data. If does fail on a few wells but interestingly the failed wells seem to complement the failed wells in interpolation workflow. I'll submit an issue to elaborate on this.

2020-04-10 21:31 UTC, bryantChhun requested changes

2020-04-10 21:31 UTC, bryantChhun commented on array_analyzer/workflows/registration_workflow.py
> +            im_roi = (np.iinfo(im_crop.dtype).max*im_crop.copy()).astype('uint8')
I'm having some difficulty with this line.  Not sure how it didn't come up earlier

"im_crop" is float64 at this point, so np.iinfo throws an error.  Additionally, we are casting float to uint8 just like  earlier, so probably just need 255*im_crop

2020-04-10 21:31 UTC, bryantChhun commented on run_array_analyzer.py
> +import array_analyzer.workflows.registration_wf as registration_wf
I believe this is now named "registration_workflow"

2020-04-10 22:30 UTC, jennyfolkesson commented on array_analyzer/workflows/registration_workflow.py
> +            im_roi = (np.iinfo(im_crop.dtype).max*im_crop.copy()).astype('uint8')
I thought you removed all the iinfo after the first one but somehow missed this one. Will remove.

2020-04-21 18:06 UTC, bryantChhun commented
I'll work on merging this into master.  There was a bit of module-movement, so I'll need to refactor a little, then retest across test data using interp/fit/well.

Will create a new branch for those changes and submit a PR here.

2020-04-21 18:11 UTC, jennyfolkesson commented
I didn't rebase robustspotdetection wrt master recently, do you want me to
do that?

On Tue, Apr 21, 2020 at 11:07 AM Bryant <notifications@github.com> wrote:

> I'll work on merging this into master. There was a bit of module-movement,
> so I'll need to refactor a little, then retest across test data using
> interp/fit/well.
>
> Will create a new branch for those changes and submit a PR here.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/czbiohub/serology-COVID19/pull/34#issuecomment-617325071>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABT3MZOKP26SRJ4WLYNEKU3RNXOFFANCNFSM4MDUHJPA>
> .
>

2020-04-22 20:51 UTC, bryantChhun reviewed
I'm ok to merge this PR as is

2020-04-22 20:51 UTC, bryantChhun commented on array_analyzer/workflows/registration_workflow.py
> +
it looks like the plots for the background images have been removed and are not present in the "debug_images" module.  Plotting background images were exactly what told me there was an issue with scaling and bitdepth.  Will this become a test instead?

2020-04-22 23:09 UTC, smguo commented
https://github.com/czbiohub/serology-COVID19/blob/ed5783b449aae66758edf701958f2d779bc5aaed/array_analyzer/transform/point_registration.py#L31

https://github.com/czbiohub/serology-COVID19/blob/ed5783b449aae66758edf701958f2d779bc5aaed/array_analyzer/extract/image_parser.py#L310
Are `icp` and `find_fiducials_markers` just old version of `particle_filter`? Is so, can we remove them?

2020-04-22 23:09 UTC, mattersoflight approved these changes
I tested the branch with last two datasets (blinded flu plate and covid concentration test plate) for accuracy of spot detection and optical density estimation. They both look great. Ready to merge with debug plots for background added back to the pipeline.

2020-04-22 23:14 UTC, smguo approved these changes
@jennyfolkesson The PR looks great. I only have some minor suggestions. Feel free to merge when you think it's ready.

2020-04-22 23:14 UTC, smguo commented on run_array_analyzer.py
> +import array_analyzer.workflows.registration_wf as registration_wf
ModuleNotFoundError: No module named 'array_analyzer.workflows.registration_wf'

2020-04-22 23:14 UTC, smguo commented on array_analyzer/workflows/registration_workflow.py
> +            im_roi = (np.iinfo(im_crop.dtype).max*im_crop.copy()).astype('uint8')
Got this: ValueError: Invalid integer data type 'f'. 
it looks like the allowed dtype is int but float is passed  

I guess this is what you were trying to do:
`im_roi = (np.iinfo(np.uint8).max*im_crop.copy()).astype('uint8')`

2020-04-22 23:14 UTC, smguo commented on array_analyzer/workflows/registration_workflow.py
> +        nbr_grid_rows, nbr_grid_cols = props_array.shape
Are `nbr_grid_rows, nbr_grid_cols` same as  `params['rows'], params['columns']`?

2020-04-22 23:14 UTC, smguo commented on run_array_analyzer.py
> +    )
Nice!

2020-04-22 23:14 UTC, smguo commented on array_analyzer/workflows/registration_workflow.py
> +
I agree with @bryantChhun. I think it would be better to keep some of the useful debug plots or move them to "debug_images" in case we need to look at them in the future. We can speed up the processing by running in regular mode instead of debug mode if the speed is the concern here.

2020-04-22 23:14 UTC, smguo commented on array_analyzer/extract/img_processing.py
> +    im_norm = black_tophat(im_norm, size=(tophat_size, tophat_size))
Just curious about the purpose of adding black tophat. Is blob detector better at detecting bright v.s. dark spots?

2020-04-22 23:14 UTC, smguo commented on array_analyzer/transform/point_registration.py
> +            if remove_outlier:
It looks like the the outlier (fiducial that is not detected) will be removed starting at the first iteration. I'm wondering if it's possible that the wrong fiducial will be removed if there happens to be a spot close to the missing fiducial in the initial grid.

2020-04-22 23:14 UTC, smguo commented on array_analyzer/transform/point_registration.py
> +                remove_spot = np.where(np.squeeze(dist) != np.amax(dist))[0]
Is this line to get the Boolean indices of the distances to keep? if so wouldn't  `dist_ids = (dist != np.amax(dist))` do the same?

2020-04-22 23:14 UTC, smguo commented on array_analyzer/transform/point_registration.py
> +                dist = dist[remove_spot]
Is `remove_spot` actually indices of the distances to keep? Maybe change the name?

2020-04-22 23:47 UTC, jennyfolkesson commented on array_analyzer/workflows/registration_workflow.py
> +        nbr_grid_rows, nbr_grid_cols = props_array.shape
Well, look at that! I didn't pay much attention to params I guess... :-)

2020-04-22 23:59 UTC, jennyfolkesson commented on array_analyzer/extract/img_processing.py
> +    im_norm = black_tophat(im_norm, size=(tophat_size, tophat_size))
No, the blob detector just needs a flag to know if the spots are bright or dark.
The black tophat is for detecting dark spots whereas a regular tophat would detect bright spots.

2020-04-23 00:03 UTC, jennyfolkesson commented on array_analyzer/transform/point_registration.py
> +            if remove_outlier:
With enough stochasticity it doesn't seem to be a problem. All the other spots need to be in agreement with the grid so if there's one spot that's not quite on the grid that will still be the one excluded would be my guess.

2020-04-23 00:03 UTC, jennyfolkesson commented on array_analyzer/transform/point_registration.py
> +                remove_spot = np.where(np.squeeze(dist) != np.amax(dist))[0]
Much better, thanks (what was I thinking...).

2020-04-23 00:04 UTC, jennyfolkesson commented on array_analyzer/transform/point_registration.py
> +                dist = dist[remove_spot]
I agree, that was a bad name. I removed that variable altogether.

2020-04-23 00:15 UTC, smguo commented on array_analyzer/transform/point_registration.py
> +            if remove_outlier:
I see. I guess the particle with the missing fiducial distance removed will have higher weight than the wrong solution, so these particles will eventually dominate through resampling. Very cool!

2020-04-23 00:59 UTC, merged

2020-04-23 01:00 UTC, bryantChhun reviewed
...