Multisero refactor
mehta-lab/multiSero pull request #91
Opened 2021-10-26 19:36 UTC by lenafb

I have refactored the multiSero codebase such that README, documentation, module names, and command line all reflect the name change from pysero to multiSero. I am suggesting this merge for naming consistency moving forward.

2021-10-26 22:49 UTC, lenafb commented
Note: first commit "pysero refactor part i" incorporates heatmap plotting functions from `heatmap-plotting` branch that existed in my local pysero repo

2021-11-03 23:00 UTC, smguo requested changes
The PR looks good @lenafb! I left a few comments on the changes to `plotting` module. Let me know if you have any questions!

2021-11-03 23:00 UTC, smguo commented on interpretation/plotting.py
> +def find_rvp_spot_type(hmap,str):
This function looks a lot like `find_spot_type`. You can probably make them a single function by doing something like `if str in name:`. Also you can slice the dataframe by column names rather than create a new dataframe and assign column by column.

2021-11-03 23:00 UTC, smguo commented on interpretation/plotting.py
> +def delta_ic50(vlp_df,fig_path,ext,index2type,str):
What is this function plotting? Maybe add doctrings?

2021-11-03 23:00 UTC, smguo commented on interpretation/plotting.py
> +    vlp_b_df = bmap.filter(regex='VLP')
You're adding quite a few heatmap plots to this the function so the function now plot both standard curves and 5 heatmaps. I would suggest separate them into two different functions to avoid confusion.

2021-11-03 23:00 UTC, smguo commented on interpretation/plotting.py
> +
Try to avoid hardcoding specific sample names in the general plotting function. You can save the serotype in the metadata tab `serum cat` or `serum type` instead of here.

2021-11-30 19:02 UTC, lenafb commented on interpretation/plotting.py
> +    vlp_b_df = bmap.filter(regex='VLP')
I just pushed changes reorganizing these two functions such that if the user is trying to evaluate the performance of individual antigens, they will get both types of plots, but if a user is wants to split subplots by antigen, they will just get  standard curves. Let me know what you think!

2021-11-30 19:05 UTC, lenafb commented
Hi @smguo, I've pushed commits addressing your previous comments, I think that this version is a little easier to parse and debug should a user need to tweak parameters.

2022-02-18 21:17 UTC, merged